name:                polylabel
version:             0.1.0.0
github:              "uebayasi/polylabel"
license:             BSD3
author:              "&quot;Masao Uebayashi&quot;"
maintainer:          "&quot;uebayasi@gmail.com&quot;"
copyright:           "&quot;Copyright: (c) 2017 Masao Uebayashi&quot;"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/uebayasi/polylabel#readme>

dependencies:
- base >= 4.7 && < 5
- containers
- lens
- linear

library:
  source-dirs: src

tests:
  polylabel-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - aeson
    - bytestring
    - hspec
    - hspec-discover
    - polylabel
